export const redGrapes: string[] =
  [
    "Alicante",
    "Barbera",
    "Blaufränkisch",
    "Cabernet Franc",
    "Cabernet",
    "Carignan",
    "Carmenere",
    "Cinsault",
    "Gamay",
    "Grenache",
    "Grignolino",
    "Malbec",
    "Mavrodaphne",
    "Mencia",
    "Merlot",
    "Mourvedre",
    "Nebbiolo",
    "Negroamaro",
    "Pinot Noir",
    "Sangiovese",
    "Saperavi",
    "Schiava",
    "Syrah",
    "Tannat",
    "Tempranillo",
    "Teroldego",
    "Touriga Nacional",
    "Zinfandel",
    "Zweigelt",
  ]

export const whiteGrapes: string[] = [

  "Albarino",
  "Aligoté",
  "Assyrtiko",
  "Chardonnay",
  "Chenin",
  "Colombard",
  "Cortese",
  "Fiano",
  "Furmint",
  "Gewürztraminer",
  "Godello",
  "Gros Manseng",
  "Gruner Veltliner",
  "Grüner Veltliner",
  "Macabeo",
  "Marsanne",
  "Muscat",
  "Petit Manseng",
  "Picpoul",
  "Pinot Gris",
  "Riesling",
  "Roussanne",
  "Sauvignon",
  "Savagnign",
  "Semillon",
  "Torrontes",
  "Trebbiano/Ugni Blanc",
  "Verdejo",
  "Verdicchio",
  "Vermentino",
  "Viognier",


]
